---
name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          # Required to grab the full history for proper pre-commit checks
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      # Cache the pre-commit environments based on the config file hash
      - name: Cache Pre-Commit Environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --color=always
            --from-ref ${{ github.event.pull_request.base.sha || github.event.before }}
            --to-ref ${{ github.event.pull_request.head.sha || github.sha }}
